# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-10 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='input',
            name='message',
        ),
        migrations.AddField(
            model_name='input',
            name='article_url',
            field=models.CharField(default='default', max_length=255),
        ),
    ]
