# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-10 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20170611_0234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
